-- CRIA TABELAS PARA ARMAZENAR EM MEMORIA AS BASES PARA TESTES FEATURE
DROP TABLE IF EXISTS TBL_LOGIN;

CREATE TABLE TBL_LOGIN(
  ID_USUARIO INT AUTO_INCREMENT  PRIMARY KEY,
  USUARIO VARCHAR(250) NOT NULL,
  SENHA VARCHAR(6) NOT NULL,
  STATUS_AUTENTICACAO BOOLEAN
);

DROP TABLE IF EXISTS TBL_CLIENTE;
  
CREATE TABLE TBL_CLIENTE(
  ID_CONTA INT AUTO_INCREMENT  PRIMARY KEY,
  NOME VARCHAR(250) NOT NULL,
  SENHA VARCHAR(6) NOT NULL,
  SALDO REAL NOT NULL,
  FEATURE BOOLEAN
);